name: Continuous Integration
on:
    push:
    pull_request:
        branches:
            - master
jobs:
    build:
        name: Build and Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install
              run: yarn

            - name: Build
              run: yarn build

            - name: Test
              run: yarn test

    codacy-coverage-reporter:
        runs-on: ubuntu-latest
        needs: build
        name: codacy-coverage-reporter
        steps:
            - uses: actions/checkout@master
            - name: Run codacy-coverage-reporter
              uses: codacy/codacy-coverage-reporter-action@master
              with:
                  project-token: ${{ secrets.CODACY_TOKEN }}
                  coverage-reports: cobertura-coverage.xml
